### ISSUE TITLE
Version bump for ruby-saml version

### ISSUE THREAD

**Issue by ahills** [PracticallyGreen/omniauth-saml#64] opened 2015-11-20 15:52 UTC
If you could make a release to include the updated ruby-saml dependency, I would much appreciate it.

**Comment by md5** [comment] 2015-11-20 22:15
@ahills I believe this still needs to be refined to require `ruby-saml` 1.1.1 or greater instead of just 1.1.0. See my comments here: https://github.com/PracticallyGreen/omniauth-saml/pull/62#issuecomment-155999629

**Comment by ahills** [comment] 2015-11-21 02:29
When I installed from current [master](d51c114d077d629aa2b4e113b6c9f3fa87ad4e78), `ruby-saml-1.1.1` was installed.

**Comment by md5** [comment] 2015-11-21 04:38
That's expected behavior. However, if someone had a Gemfile.lock with
1.1.0, they could end up breaking omniauth-saml. I still think it would be
good to prevent 1.1.0 from being installed explicitly since it's known to
be incompatible with at least some SAML integrations.

**Comment by supernova32** [comment] 2015-12-23 16:40
I created #66 for this.

**Comment by supernova32** [comment] 2016-02-03 21:17
#66 was merged, which included ruby-saml 1.1.1 so I'm closing this one.

**Closed by supernova32** 2016-02-03 21:17 UTC
